[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "INVENTORY MANAGEMENT SYSTEM - SHELFIE"
version = "1.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]


[tool.pytest.ini_options]
pythonpath = "inventory_system_test_file"